In [1]:
import pandas as pd
from glob import glob
import os
import numpy as np

In [2]:
users = pd.read_csv('profiledata/extractedUsers.csv', header=None)

In [4]:
userData = pd.read_csv('profiledata/userData.csv')

In [5]:
userData['username'].shape

(257398,)

In [6]:
len(set(userData['username']))

255608

In [7]:
userData = userData.set_index('username')

In [8]:
userData.drop_duplicates()

,location,has_location,age,is_verified,total_tweets,total_following,total_followers,total_likes,total_moments,total_lists,has_avatar,has_background,is_protected,profile_modified,tweets
username,,,,,,,,,,,,,,,
rcromwell4,NWA,1,3064,0,53001,1785,5019,38882,0,0,1,1,1,1,NaN
fola_akinnitire,"New Jersey, USA",1,2572,0,285,225,76,233,0,0,1,1,1,1,NaN
ClaireLJ13,East Devon,1,2554,0,3927,1256,555,518,0,0,1,1,1,1,NaN
icky_c,0,0,2055,0,17209,489,655,9282,0,0,1,1,1,1,NaN
greydogphoto,"Altrincham, UK",1,2415,0,13409,643,874,1023,0,0,1,1,1,1,NaN
danzzinger,Calgary,1,2539,0,1048,709,412,97,0,0,1,0,1,1,NaN
isabelfopiani,torquay australia,1,2512,0,10082,446,568,154,0,0,1,1,1,1,NaN
_herblankpage_,0,0,1300,0,470,69,41,174,0,0,1,1,1,1,NaN
Street_Ballin,"Evansville, IN-Columbia, KY",1,1687,0,2067,863,1147,7017,0,0,1,1,1,1,NaN
austca,Indiana,1,2879,0,16978,4990,3550,10736,0,0,1,1,1,1,NaN
yowatare,0,0,2899,0,15217,282,314,24404,0,0,1,1,1,1,NaN
Tantus_Pirate,"Sparks, Nv",1,1178,0,1426,895,883,7052,0,0,1,1,1,1,NaN
IcarusGlider,"Chicago, IL",1,1764,0,8482,1122,7379,3829,0,0,1,1,1,1,NaN
KristinWCarroll,"San Diego, CA",1,3399,0,447,586,512,642,0,0,1,1,1,1,NaN
Hannahfgale,London/Ipswich,1,2881,0,34932,940,17570,30002,0,0,1,1,1,1,NaN
OddsWise,"Outskirts, Northern Powerhouse",1,2530,0,20459,39,5321,3882,0,0,1,1,1,1,NaN
psychicmediumje,NY - LA,1,2987,1,27685,449,116694,39835,0,0,1,1,1,1,NaN
Hisbeautyxo,be obssesively grateful ❁,1,1896,0,39589,159,40029,12035,0,0,1,1,1,1,NaN
IPProfEvans,The Interweb,1,1857,0,7635,1117,1596,18016,0,0,1,1,1,1,NaN
HHDaySouth,"Dorset, UK",1,1078,0,3968,765,1004,5356,0,0,1,1,1,1,NaN
boroughmarket,London,1,2390,0,49694,3426,70329,34280,0,0,1,1,1,1,NaN
N8Bogdan,"Wisconsin, USA",1,954,0,500,1089,718,601,0,0,1,1,1,1,NaN
rochester,"Rochester, NY",1,3438,0,8317,8271,88352,5405,0,0,1,1,1,1,NaN
BloomingtonBrew,"Bloomington, Indiana",1,2907,0,4541,1317,3758,2029,0,0,1,1,1,1,NaN
JMcNChicago,"Downers Grove, IL",1,2575,0,43529,2368,2262,305312,0,0,1,1,1,1,NaN
BitcoinNews24,0,0,1484,0,14299,1907,4518,20,0,0,1,1,1,1,NaN
petra1207tanjab,0,0,1060,0,3,43,6,185,0,0,0,0,1,0,NaN
jazlynn_henry,0,0,1138,0,4119,522,585,8192,0,0,1,1,1,1,NaN
gatewaypundit,"St. Louis, Missouri",1,3433,1,68718,1228,100726,3522,0,0,1,1,1,1,NaN
PrincipalFrench,"Golden Valley, MN",1,2737,0,16902,14131,14249,54103,0,0,1,1,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FintechAustria,0,0,1197,0,214,195,284,335,0,0,1,0,1,1,NaN
pdegrauwe,Leuven Belgium,1,3008,0,1402,157,48801,154,0,0,1,0,1,1,NaN
escortinmumbais,"Mumbai, India",1,970,0,1404,1207,3050,2043,0,0,1,1,1,1,NaN
1NEWS9,Kenya,1,39,0,319,293,273,1895,0,0,1,1,1,1,NaN
allancho,#Vancouver #UBC,1,3712,0,4619,2734,3090,4798,0,0,1,1,1,1,NaN
jlsalmeron,"Seville, Spain",1,3041,0,554,565,254,942,0,0,1,1,1,1,NaN
NikeshMistry1,"London, England",1,952,0,777,526,261,283,0,0,1,1,1,1,NaN
burghlife48,"Pittsburgh, PA #412",1,2796,0,39502,3208,1400,24773,0,0,1,1,1,1,NaN
dayvid1234,"Vancouver, British Columbia",1,2876,0,78,675,260,5,0,0,1,0,1,1,NaN
paulmwatson,"Cape Town, South Africa",1,4245,0,173575,2640,5732,84149,0,0,1,1,1,1,NaN
ljauregui,Mexico D.F. | Zacatecas,1,3481,0,6038,828,3825,540,0,0,1,1,1,1,NaN
Mobbid,Mombasa,1,2780,0,14565,17983,17807,6200,0,0,1,1,1,1,NaN
kimmikillzombie,"Toronto, Ontario",1,3528,0,7595,8607,14555,65860,0,0,1,1,1,1,NaN
dmasley,"Heerlen, Nederland",1,2665,0,851,469,2882,915,0,0,1,1,1,1,NaN
Sonovate,UK,1,2496,0,4882,3997,1932,915,0,0,1,1,1,1,NaN
CKingLivePro,"Las Vegas, NV",1,3314,0,6778,483,3938,3386,0,0,1,0,1,1,NaN
harmongreg,"Cleveland, Ohio",1,3381,1,125324,310,34334,5028,0,0,1,1,1,1,NaN
claudeforthomme,Italy,1,2669,0,31701,2765,4757,574,0,0,1,1,1,1,NaN
syouth1,0,0,2420,0,9800,45,3599,6721,0,0,1,1,1,1,NaN
ChandakAadi,0,0,264,0,169,997,70,324,0,0,1,1,1,1,NaN
PayMet_Ltd,"London, England",1,2341,0,10074,51,263,214,0,0,1,1,1,1,NaN
consumervic,"Victoria, Australia",1,3119,1,15432,223,10167,290,0,0,1,1,1,1,NaN
dobe4ever,0,0,42,0,213,31,707,300,0,0,1,1,1,1,NaN
Oxana_spb,Санкт-Петербург,1,2467,0,114,485,344,1,0,0,1,1,1,1,NaN
GracePartakers,London - UK,1,650,0,1317,85,212,1114,0,0,1,1,1,1,NaN
NestEggAU,0,0,913,0,1197,37,272,10,0,0,1,1,1,1,NaN
holdincrypto,"To The Moon, Or Maybe Mars",1,1249,0,10791,218990,205776,735,0,0,1,1,1,1,NaN
FoxSynergy,0,0,4007,0,55233,1744,2228,17461,0,0,1,1,1,1,NaN
winlottotoday,Hong Kong,1,929,0,1602,3995,1114,115,0,0,1,1,1,1,NaN
Quantitrader,0,0,1730,0,4204,408,399,408,0,0,1,1,1,1,NaN

In [10]:
allUsers = pd.DataFrame()

for files in glob(os.getcwd() + "/*"):
    if (os.path.exists(files + "/extracted")):
        fname = files + "/extracted/combined.csv"
        tDf = pd.read_csv(fname)
        print("Extracting for {}".format(fname))
        allUsers = pd.concat([allUsers, tDf['User']])

Extracting for /home/shresthanikesh23/jupyter/CryptoTraderRemote/CryptoTrader/data_utils/twitter_data/ripple/extracted/combined.csv
Extracting for /home/shresthanikesh23/jupyter/CryptoTraderRemote/CryptoTrader/data_utils/twitter_data/dogecoin/extracted/combined.csv
Extracting for /home/shresthanikesh23/jupyter/CryptoTraderRemote/CryptoTrader/data_utils/twitter_data/monero/extracted/combined.csv
Extracting for /home/shresthanikesh23/jupyter/CryptoTraderRemote/CryptoTrader/data_utils/twitter_data/stellar/extracted/combined.csv
Extracting for /home/shresthanikesh23/jupyter/CryptoTraderRemote/CryptoTrader/data_utils/twitter_data/litecoin/extracted/combined.csv

/home/shresthanikesh23/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Extracting for /home/shresthanikesh23/jupyter/CryptoTraderRemote/CryptoTrader/data_utils/twitter_data/ethereum/extracted/combined.csv
Extracting for /home/shresthanikesh23/jupyter/CryptoTraderRemote/CryptoTrader/data_utils/twitter_data/dash/extracted/combined.csv
Extracting for /home/shresthanikesh23/jupyter/CryptoTraderRemote/CryptoTrader/data_utils/twitter_data/bitcoin/extracted/combined.csv

In [11]:
newUsers = pd.DataFrame()
newUsers[0] = allUsers[0].unique()

In [12]:
len(newUsers[0])

298641

In [13]:
len(allUsers[0])

1152124

In [14]:
userData = pd.read_csv(os.getcwd() + "/profiledata/userData.csv")
userTweets = pd.read_csv(os.getcwd() + "/profiledata/userTweets.csv")

/home/shresthanikesh23/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [15]:
userData = userData.set_index('username')

In [16]:
userData.shape

(257398, 15)

In [17]:
userData = userData.drop_duplicates()

In [18]:
userData.shape

(255615, 15)

In [19]:
userData = userData.reset_index()

In [20]:
userTweets = userTweets.set_index(['User', 'ID'])

In [21]:
userTweets.shape

(4135304, 5)

In [22]:
userTweets = userTweets.drop_duplicates()

In [23]:
userTweets.shape

(2559264, 5)

In [24]:
userTweets = userTweets.reset_index()

In [25]:
userTweets.User.unique().shape

(244423,)

In [26]:
firstdiff = np.setdiff1d(userTweets.User,  userData.username)

KeyboardInterrupt:

In [ ]:
seconddiff = np.setdiff1d(userData.User,  userTweets.username)